version: '3.1'

services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  api:
    restart: always
    build: ./backend
    ports:
      - '5050:5050'
    volumes:
      - ./backend:/app
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Password123
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Password123
      ME_CONFIG_MONGODB_URL: mongodb://root:Password123@mongo:27017/
    depends_on:
      - mongo

volumes:
  mongodb_data: